[project]
name = "ai-trip-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "streamlit>=1.48.1",
]

[tool.uv.workspace]
members = [
    "AI_Travel_Planner",
    "AI_Planner",
]
